name: publish to ghpages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      working-directory: LadyBot.Wasm
      run: dotnet restore
    - name: Build
      working-directory: LadyBot.Wasm
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      working-directory: LadyBot.Wasm
      run: dotnet publish -c Release --no-build -o ../publish/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish
