name: publish to ghpages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build
      working-directory: ./LadyBot.Wasm
      run: dotnet build --configuration Release
    - name: Publish
      working-directory: ./LadyBot.Wasm
      run: dotnet publish -c Release --no-build -o ../publish/
    - name: Fix publish
      working-directory: ./publish
      run: |
        mv wwwroot/* .
        rmdir wwwroot
        sed -i -e "s/base href=\".*\"/base href=\"\/LadyBot\//" index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish
